/**
 * Sound + haptics for المندس.
 *
 * All assets are generated by `scripts/gen-sounds.js` — see that file for the
 * synthesis. This module is only playback policy.
 *
 * Two things drove the design:
 *
 * 1. A single `expo-audio` player cannot overlap itself. Tapping quickly would
 *    cut the previous blip off mid-flight, which sounds broken. So each effect
 *    gets a small round-robin pool of players.
 * 2. Players load asynchronously. Creating all 8 sounds up front stalls the
 *    first screen, so pools are built lazily on an effect's first use and then
 *    reused for the rest of the session.
 */

import AsyncStorage from "@react-native-async-storage/async-storage";
import {
  AudioPlayer,
  createAudioPlayer,
  setAudioModeAsync,
} from "expo-audio";
import * as Haptics from "expo-haptics";
import { useEffect, useState } from "react";

const MUTE_KEY = "imposter_muted_v1";

/** How many concurrent copies of each effect we allow. */
const POOL_SIZE = 3;

const SOURCES = {
  tap: require("../assets/audio/tap.wav"),
  select: require("../assets/audio/select.wav"),
  back: require("../assets/audio/back.wav"),
  confirm: require("../assets/audio/confirm.wav"),
  reveal: require("../assets/audio/reveal.wav"),
  win: require("../assets/audio/win.wav"),
} as const;
// Note: there is deliberately no imposter-specific effect. The reveal step must
// sound identical for every player, or the room hears who the imposter is.

export type SoundName = keyof typeof SOURCES;

/** Per-effect mix levels, so nothing jumps out relative to the rest. */
const VOLUME: Record<SoundName, number> = {
  tap: 0.55,
  select: 0.6,
  back: 0.5,
  confirm: 0.7,
  reveal: 0.75,
  win: 0.8,
};

/** Haptic paired with each effect. `null` = no vibration. */
const HAPTIC: Record<SoundName, Haptics.ImpactFeedbackStyle | "success" | "warning" | null> = {
  tap: Haptics.ImpactFeedbackStyle.Light,
  select: Haptics.ImpactFeedbackStyle.Light,
  back: null,
  confirm: Haptics.ImpactFeedbackStyle.Medium,
  reveal: Haptics.ImpactFeedbackStyle.Medium,
  win: "success",
};

type Pool = { players: AudioPlayer[]; next: number };

const pools = new Map<SoundName, Pool>();
let ambient: AudioPlayer | null = null;
let ambientWanted = false;

let muted = false;
let hydrated = false;
const listeners = new Set<() => void>();

function notify() {
  for (const l of listeners) l();
}

// ------------------------------------------------------------------ lifecycle

/**
 * Call once at app start. Restores the mute preference and configures the
 * session so iOS does not silence us when the physical ringer switch is off.
 */
export async function initAudio(): Promise<void> {
  try {
    const raw = await AsyncStorage.getItem(MUTE_KEY);
    muted = raw === "1";
  } catch {
    // A missing preference is not worth surfacing; default to unmuted.
  }
  hydrated = true;
  notify();

  try {
    await setAudioModeAsync({
      playsInSilentMode: true,
      interruptionMode: "mixWithOthers",
      shouldPlayInBackground: false,
      allowsRecording: false,
    });
  } catch {
    // Audio mode is a nice-to-have; never block startup on it.
  }
}

// --------------------------------------------------------------------- effects

function poolFor(name: SoundName): Pool | null {
  let pool = pools.get(name);
  if (pool) return pool;
  try {
    const players = Array.from({ length: POOL_SIZE }, () => {
      const p = createAudioPlayer(SOURCES[name]);
      p.volume = VOLUME[name];
      return p;
    });
    pool = { players, next: 0 };
    pools.set(name, pool);
    return pool;
  } catch {
    // If the native module is unavailable the game must still be playable.
    return null;
  }
}

function fireHaptic(name: SoundName) {
  const h = HAPTIC[name];
  if (h === null) return;
  // Fire and forget: haptics no-op on unsupported devices and in Low Power Mode,
  // so nothing may depend on the result.
  if (h === "success") {
    void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success).catch(() => {});
  } else if (h === "warning") {
    void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Warning).catch(() => {});
  } else {
    void Haptics.impactAsync(h).catch(() => {});
  }
}

/** Plays a one-shot effect (and its paired haptic). Safe to call anywhere. */
export function play(name: SoundName): void {
  if (muted) return;
  fireHaptic(name);

  const pool = poolFor(name);
  if (!pool) return;
  const player = pool.players[pool.next];
  pool.next = (pool.next + 1) % pool.players.length;
  try {
    // expo-audio leaves the playhead at the end after finishing, so a replay
    // needs an explicit rewind.
    player.seekTo(0);
    player.play();
  } catch {
    // Ignore transient playback errors — never let a sound break an interaction.
  }
}

// --------------------------------------------------------------------- ambient

/** Starts (or resumes) the looping home-screen pad. */
export function startAmbient(): void {
  ambientWanted = true;
  if (muted) return;
  try {
    if (!ambient) {
      ambient = createAudioPlayer(require("../assets/audio/home_loop.wav"));
      ambient.loop = true;
      // The pad is synthesised with a lot of headroom (it peaks around 20% of
      // full scale), so this needs to sit high to be audible on a phone speaker.
      ambient.volume = 0.85;
    }
    ambient.play();
  } catch {
    ambient = null;
  }
}

/** Pauses the pad and stops wanting it (leaving the home screen). */
export function stopAmbient(): void {
  ambientWanted = false;
  try {
    ambient?.pause();
  } catch {
    // Nothing to recover from.
  }
}

// ------------------------------------------------------------------ mute state

export function isMuted(): boolean {
  return muted;
}

export function setMuted(next: boolean): void {
  muted = next;
  notify();
  void AsyncStorage.setItem(MUTE_KEY, next ? "1" : "0").catch(() => {});

  if (next) {
    try {
      ambient?.pause();
    } catch {
      /* ignore */
    }
  } else if (ambientWanted) {
    startAmbient();
  }
}

export function toggleMuted(): void {
  setMuted(!muted);
}

/** Subscribes a component to mute changes. */
export function useMuted(): boolean {
  const [value, setValue] = useState(muted);
  useEffect(() => {
    const listener = () => setValue(muted);
    listeners.add(listener);
    // The preference may have hydrated between render and effect.
    if (hydrated) listener();
    return () => {
      listeners.delete(listener);
    };
  }, []);
  return value;
}
